site_name: Optimization Tutorial
repo_url: https://github.com/SimonBlanke/optimization-tutorial

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - toc:
      title: On this page

plugins:
  - glightbox
  - macros

theme:
  name: material

  icon:
    repo: fontawesome/brands/square-github

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue grey
      accent: deep purple
      toggle:
        icon: material/brightness-5
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      accent: deep purple
      toggle:
        icon: material/brightness-3
        name: Switch to light mode

  features:
    - navigation.indexes

extra_css:
  - css/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/blanke_simon
    - icon: fontawesome/brands/github
      link: https://github.com/SimonBlanke/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/simon-blanke/

nav:
  - Home:
      - Optimization Tutorial: index.md

  - Optimization Algorithms:
      - Optimization Template: optimizers/hill_climbing/page.md